version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --init-file /data/init/create-tables.sql
    #ports:
     # - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
      - ./create-tables.sql:/data/init/create-tables.sql

  api:
    build:
      context: .
      dockerfile: ./build/grpc/Dockerfile
    environment:
      DATABASE: db
      REDIS_PORT: cache:6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db